name: trading-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  # Core packages
  - pip
  - numpy
  - pandas
  - matplotlib=3.7.1
  - jupyter
  - ipykernel
  # pip packages
  - pip:
    - yfinance==0.2.18
    - tensorflow==2.10.0
    - keras-tcn==3.4.0
    - websockets==12.0
    - orjson==3.9.10